src/Plugins/Nop.Plugin.Widgets.qBoSlider/Models/Admin/WidgetZones/AddWidgetZoneSlideModel.cs
using Nop.Web.Framework.Models;
using Nop.Web.Framework.Mvc.ModelBinding;
using System;
using System.Collections.Generic;

namespace Nop.Plugin.Widgets.qBoSlider.Models.Admin.WidgetZones
{
    /// <summary>
    /// Represents add widget zone slide model
    /// </summary>
    public class AddWidgetZoneSlideModel : BaseSearchModel
    {
        /// <summary>
        /// Gets or sets widget zone unique id number
        /// </summary>
        public int WidgetZoneId { get; set; }

        /// <summary>
        /// Gets or sets seleceted slides id numbers
        /// </summary>
        public IList<int> SelecetedSlideIds { get; set; } = new List<int>();

        /// <summary>
        /// Represents slide list model
        /// </summary>
        public class SlidePagedListModel : BasePagedListModel<SlideModel>
        {

        }

        /// <summary>
        /// Represents slide for slide searching
        /// </summary>
        public class SlideModel : BaseNopEntityModel
        {
            /// <summary>
            /// Gets or sets slide background picture url
            /// </summary>
            [NopResourceDisplayName("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.AddWidgetZoneSlide.Fields.PictureUrl")]
            public string PictureUrl { get; set; }

            /// <summary>
            /// Gets or sets slide publishing start date 
            /// </summary>
            [NopResourceDisplayName("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.AddWidgetZoneSlide.Fields.StartDateUtc")]
            public DateTime? StartDateUtc { get; set; }

            /// <summary>
            /// Gets or sets slide publishing end date
            /// </summary>
            [NopResourceDisplayName("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.AddWidgetZoneSlide.Fields.EndDateUtc")]
            public DateTime? EndDateUtc { get; set; }

            /// <summary>
            /// Gets or sets slide publish value
            /// </summary>
            [NopResourceDisplayName("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.AddWidgetZoneSlide.Fields.Published")]
            public bool Published { get; set; }
        }
    }
}

src/Plugins/Nop.Plugin.Widgets.qBoSlider/Models/Admin/WidgetZones/WidgetZoneSearchModel.cs
using Nop.Web.Framework.Models;
using Nop.Web.Framework.Mvc.ModelBinding;

namespace Nop.Plugin.Widgets.qBoSlider.Models.Admin.WidgetZones
{
    /// <summary>
    /// Represents widget zone search model
    /// </summary>
    public partial class WidgetZoneSearchModel : BaseSearchModel, IWidgetZoneSearchModel
    {
        /// <summary>
        /// Gets or sets searching widget zone friendly name
        /// </summary>
        public string SearchWidgetZoneName { get; set; }

        /// <summary>
        /// Gets or sets searching widget zone system name
        /// </summary>
        public string SearchWidgetZoneSystemName { get; set; }

        /// <summary>
        /// Represents widget zone paged list model
        /// </summary>
        public class WidgetZoneList : BasePagedListModel<WidgetZoneListItem>
        {

        }

        /// <summary>
        /// Represents widget zone paged list item
        /// </summary>
        public class WidgetZoneListItem : BaseNopEntityModel
        {
            /// <summary>
            /// Gets or sets widget zone friendly name
            /// </summary>
            public string Name { get; set; }

            /// <summary>
            /// Gets or sets widget zone system name
            /// </summary>
            public string SystemName { get; set; }

            /// <summary>
            /// Gets or sets value wether indicating widget zone publish state
            /// </summary>
            public bool Published { get; set; }
        }
    }
}

src/Plugins/Nop.Plugin.Widgets.qBoSlider/Models/Admin/WidgetZones/WidgetZoneSlideModel.cs
using Nop.Web.Framework.Models;
using Nop.Web.Framework.Mvc.ModelBinding;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Nop.Plugin.Widgets.qBoSlider.Models.Admin.WidgetZones
{
    /// <summary>
    /// Represents widget zone slide model
    /// </summary>
    public class WidgetZoneSlideModel : BaseNopEntityModel, ILocalizedModel<WidgetZoneSlideModel.LocalizationModel>
    {
        /// <summary>
        /// Gets or sets slide picture id number
        /// </summary>
        [NopResourceDisplayName("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.WidgetZoneSlide.Fields.PictureId")]
        [UIHint("Picture")]
        public int PictureId { get; set; }

        /// <summary>
        /// Gets or sets slide picture url
        /// </summary>
        public string PictureUrl { get; set; }

        /// <summary>
        /// Gets or sets slide entity id number
        /// </summary>
        public int SlideId { get; set; }

        /// <summary>
        /// Gets or sets slide override HTML content. 
        /// </summary>
        [NopResourceDisplayName("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.WidgetZoneSlide.Fields.OverrideDescription")]
        public string OverrideDescription { get; set; }

        /// <summary>
        /// Gets or sets slide display order
        /// </summary>
        [NopResourceDisplayName("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.WidgetZoneSlide.Fields.DisplayOrder")]
        public int DisplayOrder { get; set; }

        /// <summary>
        /// Gets or sets localized locale models
        /// </summary>
        public IList<LocalizationModel> Locales { get; set; } = new List<LocalizationModel>();

        /// <summary>
        /// Represents widget zone slide overriding HTML content localization model
        /// </summary>
        public class LocalizationModel : ILocalizedLocaleModel
        {
            /// <summary>
            /// Gets or sets slide localized HTML content. 
            /// </summary>
            [NopResourceDisplayName("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.WidgetZoneSlide.Fields.OverrideDescription")]
            public string OverrideDescription { get; set; }

            /// <summary>
            /// Gets or sets the language identifier
            /// </summary>
            public int LanguageId { get; set; }
        }
    }
}

src/Plugins/Nop.Plugin.Widgets.qBoSlider/Controllers/qBoWidgetZoneController.cs
//Copyright 2020 Alexey Prokhorov

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at

//    http://www.apache.org/licenses/LICENSE-2.0

//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

using Microsoft.AspNetCore.Mvc;
using Nop.Core.Caching;
using Nop.Plugin.Widgets.qBoSlider.Domain;
using Nop.Plugin.Widgets.qBoSlider.Factories.Admin;
using Nop.Plugin.Widgets.qBoSlider.Models.Admin.WidgetZones;
using Nop.Plugin.Widgets.qBoSlider.Service;
using Nop.Services.Configuration;
using Nop.Services.Customers;
using Nop.Services.Localization;
using Nop.Services.Messages;
using Nop.Services.Security;
using Nop.Services.Stores;
using Nop.Web.Framework;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Mvc;
using Nop.Web.Framework.Mvc.Filters;
using System;
using System.Linq;

namespace Nop.Plugin.Widgets.qBoSlider.Controllers
{
    /// <summary>
    /// Represents plugin widget zone controller
    /// </summary>
    [AuthorizeAdmin]
    [Area(AreaNames.Admin)]
    public class qBoWidgetZoneController : BasePluginController
    {
        #region Fields

        private readonly IAclService _aclService;
        private readonly ICustomerService _customerService;
        private readonly ILocalizationService _localizationService;
        private readonly ILocalizedEntityService _localizedEntityService;
        private readonly INotificationService _notificationService;
        private readonly IPermissionService _permissionService;
        private readonly ISettingService _settingService;
        private readonly IStaticCacheManager _staticCacheManager;
        private readonly IStoreMappingService _storeMappingService;
        private readonly IStoreService _storeService;
        private readonly IWidgetZoneModelFactory _widgetZoneModelFactory;
        private readonly IWidgetZoneSlideModelFactory _widgetZoneSlideModelFactory;
        private readonly IWidgetZoneService _widgetZoneService;
        private readonly IWidgetZoneSlideService _widgetZoneSlideService;

        #endregion

        #region Constructor

        public qBoWidgetZoneController(IAclService aclService,
            ICustomerService customerService,
            ILocalizationService localizationService,
            ILocalizedEntityService localizedEntityService,
            INotificationService notificationService,
            IPermissionService permissionService,
            ISettingService settingService,
            IStoreMappingService storeMappingService,
            IStoreService storeService,
            IWidgetZoneModelFactory widgetZoneModelFactory,
            IWidgetZoneSlideModelFactory widgetZoneSlideModelFactory,
            IWidgetZoneService widgetZoneService,
            IWidgetZoneSlideService widgetZoneSlideService)
        {
            _aclService = aclService;
            _customerService = customerService;
            _localizationService = localizationService;
            _localizedEntityService = localizedEntityService;
            _notificationService = notificationService;
            _permissionService = permissionService;
            _settingService = settingService;
            _storeMappingService = storeMappingService;
            _storeService = storeService;
            _widgetZoneModelFactory = widgetZoneModelFactory;
            _widgetZoneSlideModelFactory = widgetZoneSlideModelFactory;
            _widgetZoneService = widgetZoneService;
            _widgetZoneSlideService = widgetZoneSlideService;
        }

        #endregion

        #region Utilites

        /// <summary>
        /// Save widget zone ACL
        /// </summary>
        /// <param name="model">Widget zone model</param>
        /// <param name="widgetZone">Widget zone entity</param>
        protected virtual void SaveWidgetZoneAcl(WidgetZoneModel model, WidgetZone widgetZone)
        {
            var existingAclRecords = _aclService.GetAclRecords(widgetZone);
            var allCustomerRoles = _customerService.GetAllCustomerRoles(true);

            //processing customer roles dependencies
            foreach (var customerRole in allCustomerRoles)
            {
                if (model.SelectedCustomerRoleIds.Contains(customerRole.Id))
                {
                    //add new role dependecy
                    if (existingAclRecords.Count(acl => acl.CustomerRoleId == customerRole.Id) == 0)
                        _aclService.InsertAclRecord(widgetZone, customerRole.Id);
                }
                else
                {
                    //remove role dependency
                    var aclRecordToDelete = existingAclRecords.FirstOrDefault(acl => acl.CustomerRoleId == customerRole.Id);
                    if (aclRecordToDelete != null)
                        _aclService.DeleteAclRecord(aclRecordToDelete);
                }
            }
        }

        /// <summary>
        /// Save widget zone store mappings
        /// </summary>
        /// <param name="model">Widget zone model</param>
        /// <param name="widgetZone">Widget zone entity</param>
        protected virtual void SaveWidgetZoneStoreMappings(WidgetZoneModel model, WidgetZone widgetZone)
        {
            var existingStoreMappings = _storeMappingService.GetStoreMappings(widgetZone);
            var allStores = _storeService.GetAllStores();

            //process store mappings
            foreach (var store in allStores)
            {
                if (model.SelectedStoreIds.Contains(store.Id))
                {
                    //add new store mapping
                    if (existingStoreMappings.Count(sm => sm.StoreId == store.Id) == 0)
                        _storeMappingService.InsertStoreMapping(widgetZone, store.Id);
                }
                else
                {
                    //remove store mapping
                    var storeMappingToDelete = existingStoreMappings.FirstOrDefault(sm => sm.StoreId == store.Id);
                    if (storeMappingToDelete != null)
                        _storeMappingService.DeleteStoreMapping(storeMappingToDelete);
                }
            }
        }

        #endregion

        #region Widget Zone

        public virtual IActionResult List()
        {
            //return access denied page if customer has no permissions
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageWidgets))
                return AccessDeniedView();

            var model = new WidgetZoneSearchModel();
            model.SetGridPageSize();

            return View("~/Plugins/Widgets.qBoSlider/Views/Admin/WidgetZone/List.cshtml", model);
        }

        [HttpPost]
        public virtual IActionResult List(WidgetZoneSearchModel searchModel)
        {
            //return access denied result if customer has no permissions
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageWidgets))
                return AccessDeniedDataTablesJson();

            var gridModel = _widgetZoneModelFactory.PrepareWidgetZonePagedListModel(searchModel);

            return Json(gridModel);
        }

        public virtual IActionResult Create()
        {
            //return access denied page if customer has no permissions
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageWidgets))
                return AccessDeniedView();

            var model = new WidgetZoneModel();

            //prepare widget zone model
            _widgetZoneModelFactory.PrepareWidgetZoneModel(model, null);
            //prepare widget zone ACL
            _widgetZoneModelFactory.PrepareAclModel(model, null);
            //prepare widget zone store mappings
            _widgetZoneModelFactory.PrepareStoreMappings(model, null);

            return View("~/Plugins/Widgets.qBoSlider/Views/Admin/WidgetZone/Create.cshtml", model);
        }

        [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
        public virtual IActionResult Create(WidgetZoneModel model, bool continueEditing)
        {
            //return access denied page if customer has no permissions
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageWidgets))
                return AccessDeniedView();

            //return view if model state isn't valid
            if (!ModelState.IsValid)
            {
                //prepare model values
                model = _widgetZoneModelFactory.PrepareWidgetZoneModel(model, null);
                //prepare widget zone ACL
                _widgetZoneModelFactory.PrepareAclModel(model, null);
                //prepare widget zone store mappings
                _widgetZoneModelFactory.PrepareStoreMappings(model, null);


                return View("~/Plugins/Widgets.qBoSlider/Views/Admin/WidgetZone/Create.cshtml", model);
            }

            var widgetZone = new WidgetZone()
            {
                //put slider properties
                ArrowNavigationDisplayingTypeId = model.ArrowNavigationDisplayingTypeId,
                BulletNavigationDisplayingTypeId = model.BulletNavigationDisplayingTypeId,
                AutoPlay = model.AutoPlay,
                AutoPlayInterval = model.AutoPlayInterval,
                MinDragOffsetToSlide = model.MinDragOffsetToSlide,
                MinSlideWidgetZoneWidth = model.MinSlideWidgetZoneWidth,
                MaxSlideWidgetZoneWidth = model.MaxSlideWidgetZoneWidth,
                MinSlideWidgetZoneHeight = model.MinSlideWidgetZoneHeight,
                MaxSlideWidgetZoneHeight = model.MaxSlideWidgetZoneHeight,
                SlideDuration = model.SlideDuration,

src/Plugins/Nop.Plugin.Widgets.qBoSlider/Views/Admin/WidgetZone/AddWidgetZoneSlidePopup.cshtml
@model AddWidgetZoneSlideModel

@{
    Layout = "_AdminPopupLayout";

    //page title
    ViewBag.Title = T("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.WidgetZone.AddWidgetZoneSlidePopup").Text;
}

<style type="text/css">
    #slides-grid img {
        max-height: 100px;
    }
</style>
@if (ViewBag.RefreshPage == true)
{
    <script>
        try {window.opener.document.forms['@(Context.Request.Query["formId"])'].@(Context.Request.Query["btnId"]).click();}
        catch (e){}
        window.close();
    </script>
}
else
{
    <form asp-controller="qBoWidgetZone" asp-action="AddWidgetZoneSlidePopup"
          asp-route-categoryId="@Context.Request.Query["widgetZoneId"]"
          asp-route-btnId="@Context.Request.Query["btnId"]"
          asp-route-formId="@Context.Request.Query["formId"]">

        <input asp-for="WidgetZoneId" type="hidden" />
        <div class="content-header clearfix">
            <h1 class="pull-left">
                @T("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.WidgetZone.WidgetZoneSlide.AddNew")
            </h1>
            <div class="pull-right">
                &nbsp;
            </div>
        </div>
        <div class="content">
            <div class="form-horizontal">
                <div class="panel-group">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            @await  Html.PartialAsync("Table", new DataTablesModel
                       {
                           Name = "slides-grid",
                           UrlRead = new DataUrl("AddSlideList", "qBoWidgetZone", null),
                           Length = Model.PageSize,
                           LengthMenu = Model.AvailablePageSizes,
                           ColumnCollection = new List<ColumnProperty>
                                   {
                                       new ColumnProperty(nameof(AddWidgetZoneSlideModel.SlideModel.Id))
                                       {
                                           IsMasterCheckBox = true,
                                           Render = new RenderCheckBox(nameof(AddWidgetZoneSlideModel.SelecetedSlideIds)),
                                           ClassName = NopColumnClassDefaults.CenterAll,
                                           Width = "50"
                                       },
                                       new ColumnProperty(nameof(AddWidgetZoneSlideModel.SlideModel.PictureUrl))
                                       {
                                           Render = new RenderPicture(),
                                           ClassName = NopColumnClassDefaults.CenterAll,
                                           Title = T("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.AddWidgetZoneSlide.Fields.PictureUrl").Text,
                                           Width = "300"
                                       },
                                       new ColumnProperty(nameof(AddWidgetZoneSlideModel.SlideModel.StartDateUtc))
                                       {
                                           Title = T("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.AddWidgetZoneSlide.Fields.StartDateUtc").Text,
                                           Render = new RenderDate(),
                                           Width = "150"
                                       },
                                       new ColumnProperty(nameof(AddWidgetZoneSlideModel.SlideModel.EndDateUtc))
                                       {
                                           Title = T("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.AddWidgetZoneSlide.Fields.EndDateUtc").Text,
                                           Render = new RenderDate(),
                                           Width = "150"
                                       },
                                       new ColumnProperty(nameof(AddWidgetZoneSlideModel.SlideModel.Published))
                                       {
                                           Title = T("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.AddWidgetZoneSlide.Fields.Published").Text,
                                           Render = new RenderBoolean(),
                                           ClassName = NopColumnClassDefaults.CenterAll,
                                           Width = "100"
                                       }
                                   }
                       })
                        </div>
                        <div class="panel-footer">
                            <button type="submit" name="save" class="btn bg-blue">
                                <i class="fa fa-floppy-o"></i>
                                @T("Admin.Common.Save")
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
}

src/Plugins/Nop.Plugin.Widgets.qBoSlider/Views/Admin/WidgetZone/Create.cshtml
@model WidgetZoneModel
@{
    //page title
    ViewBag.Title = T("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.WidgetZone.Create").Text;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("Baroque-qBoSlider-WidgetZone");
    Layout = "_AdminLayout";
}

<form asp-controller="qBoWidgetZone" asp-action="Create" method="post" id="widget-zone-form">
    <div class="content-header clearfix">
        <h1 class="pull-left">
            @T("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.WidgetZone.Create")
            <small>
                <i class="fa fa-arrow-circle-left"></i>
                <a asp-action="List">@T("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.WidgetZone.BackToList")</a>
            </small>
        </h1>
        <div class="pull-right">
            <button type="submit" name="save" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = "qBo_slider_widget_create_buttons" })
        </div>
    </div>
    <div class="content-header clearfix">
        <div class="ui-state-highlight ui-corner-all" style="margin-top:0;padding:10px">
            <span class="ui-icon ui-icon-info" style="float:left;margin-right:.3em"></span>
            @T("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.ClearNopCommerceWidgetZoneAfterNewWidgetZoneCreation")
        </div>
    </div>
    @await Html.PartialAsync("~/Plugins/Widgets.qBoSlider/Views/Admin/WidgetZone/_CreateOrUpdate.cshtml", Model)
</form>

src/Plugins/Nop.Plugin.Widgets.qBoSlider/Views/Admin/WidgetZone/Edit.cshtml
@model WidgetZoneModel
@{
    //page title
    ViewBag.Title = T("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.WidgetZone.Edit").Text;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("Baroque-qBoSlider-WidgetZone");
    Layout = "~/Plugins/Widgets.qBoSlider/Views/Admin/_qBoLayout.cshtml";
}

<form asp-controller="qBoWidgetZone" asp-action="Edit" method="post" id="widget-zone-form">
    <div class="content-header clearfix">
        <h1 class="pull-left">
            @T("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.WidgetZone.Edit") - @Model.Name
            <small>
                <i class="fa fa-arrow-circle-left"></i>
                <a asp-action="List">@T("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.WidgetZone.BackToList")</a>
            </small>
        </h1>
        <div class="pull-right">
            <button type="submit" name="save" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            <span id="widget-zone-delete" class="btn bg-red">
                <i class="fa fa-trash-o"></i>
                @T("Admin.Common.Delete")
            </span>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = "qBo_slider_widget_edit_buttons" })
        </div>
    </div>
    @await Html.PartialAsync("~/Plugins/Widgets.qBoSlider/Views/Admin/WidgetZone/_CreateOrUpdate.cshtml", Model)
</form>
<nop-delete-confirmation asp-model-id="@Model.Id" asp-button-id="widget-zone-delete" />

src/Plugins/Nop.Plugin.Widgets.qBoSlider/Views/Admin/WidgetZone/EditWidgetZoneSlidePopup.cshtml
@model WidgetZoneSlideModel

@{
    Layout = "_AdminPopupLayout";

    //page title
    ViewBag.Title = T("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.WidgetZone.EditWidgetZoneSlidePopup").Text;
}


<style type="text/css">
    img.thumbnail {
        max-height: 100px;
    }
</style>
@if (ViewBag.RefreshPage == true)
{
    <script>
        try {window.opener.document.forms['@(Context.Request.Query["formId"])'].@(Context.Request.Query["btnId"]).click();}
        catch (e){}
        window.close();
    </script>
}

<form asp-controller="qBoWidgetZone" asp-action="EditWidgetZoneSlidePopup"
      asp-route-btnId="@Context.Request.Query["btnId"]"
      asp-route-formId="@Context.Request.Query["formId"]">
    <div class="content-header clearfix">
        <h1 class="pull-left">
            @T("Nop.Plugin.Baroque.Widgets.qBoSlider.Admin.WidgetZone.EditWidgetZoneSlidePopup.Details")
        </h1>
        <div class="pull-right">
            <button type="submit" name="save" class="btn bg-blue">
                @T("Admin.Common.Save")
            </button>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = "qBo_slider_widget_zone_slide_edit_buttons", additionalData = Model })
        </div>
    </div>
    <input asp-for="Id" type="hidden" />
    <input asp-for="SlideId" type="hidden" />

    <div class="content">
        <div class="form-horizontal">
            <div class="panel-group">
                @await Component.InvokeAsync("AdminWidget", new { widgetZone = "qBo_slider_widget_zone_slide_edit_details_top", additionalData = Model })
                <div class="panel panel-default panel-popup">
                    <div class="panel-body">
                        <div class="form-group">
                            <div class="col-sm-3">
                                <nop-label asp-for="PictureId" />
                            </div>
                            <div class="col-sm-9">
                                <img class="thumbnail" src="@Model.PictureUrl" />
                            </div>
                        </div>
                        @(Html.LocalizedEditor<WidgetZoneSlideModel, WidgetZoneSlideModel.LocalizationModel>("widget-zone-slide-localized",@<div>
                                <div class="form-group">
                                    <div class="col-sm-3">
                                        <nop-label asp-for="@Model.Locales[item].OverrideDescription" />
                                    </div>
                                    <div class="col-sm-9">
                                        <nop-editor asp-for="@Model.Locales[item].OverrideDescription" />
                                        <span asp-validation-for="@Model.Locales[item].OverrideDescription"></span>
                                    </div>
                                </div>
                                <input type="hidden" asp-for="@Model.Locales[item].LanguageId" />
                            </div>,@<div>
                                <div class="form-group">
                                    <div class="col-sm-3">
                                        <nop-label asp-for="OverrideDescription" />
                                    </div>
                                    <div class="col-sm-9">
                                        <nop-textarea asp-for="OverrideDescription" asp-required="true" />
                                        <span asp-validation-for="OverrideDescription"></span>
                                    </div>
                                </div>
                            </div>))
                        <div class="form-group">
                            <div class="col-sm-3">
                                <nop-label asp-for="DisplayOrder" />
                            </div>
                            <div class="col-sm-9">
                                <nop-editor asp-for="DisplayOrder" />
                                <span asp-validation-for="DisplayOrder"></span>
                            </div>
                        </div>
                    </div>
                </div>
                @await Component.InvokeAsync("AdminWidget", new { widgetZone = "qBo_slider_widget_zone_slide_edit_details_bottom", additionalData = Model })
            </div>
        </div>
    </div>

</form>